version: "3.8"
name: "layers-services"
services: 
  db:
    image: "postgres"
    restart: always
    container_name: "layers-db"
    env_file:
      - .env
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB:=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes: 
      - database-data:/var/lib/postgresql-data/
    ports:
      - 5432:5432
    
volumes:
  database-data: